package cilok.com.lapakjahit.fragments;


import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.widget.SwipeRefreshLayout;
import android.support.v7.widget.GridLayoutManager;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import java.util.ArrayList;

import cilok.com.lapakjahit.R;
import cilok.com.lapakjahit.activities.LoginActivity;
import cilok.com.lapakjahit.adapters.AdapterFavorite;
import cilok.com.lapakjahit.callback.GetFavoritesCallback;
import cilok.com.lapakjahit.controller.UserController;
import cilok.com.lapakjahit.entity.ProductFavorite;
import cilok.com.lapakjahit.tasks.TaskFavorite;


/**
 * A simple {@link Fragment} subclass.
 */
public class FragmentFavorit extends Fragment implements SwipeRefreshLayout.OnRefreshListener {

    UserController userController;
//    ImageView mImageViewBelomLogin;
//    TextView mTextViewBelomLogin;
//    Button mButtonLogin;


    private SwipeRefreshLayout mSwipeRefreshLayoutFavorite;
    //the recylerview containing showing all our message;
    private RecyclerView mRecylerFavoriteProduct;
    //the TextView containing error messages generated by Volley
    private TextView mTextError;

    private AdapterFavorite mAdapter;
    private RecyclerView.LayoutManager mLayoutManager;
    private ArrayList<ProductFavorite> mListFavorites = new ArrayList<>();

    public FragmentFavorit() {
        // Required empty public constructor

    }
    Context context;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View layout = inflater.inflate(R.layout.fragment_favorit, container, false);
        context = layout.getContext();
        userController = new UserController(getActivity());

//        mButtonLogin = (Button)layout.findViewById(R.id.button_login);
//        mButtonLogin.setOnClickListener(new View.OnClickListener() {
//            @Override
//            public void onClick(View view) {
//                Intent intent = new Intent(context, LoginActivity.class);
//                startActivity(intent);
//            }
//        });
//        mImageViewBelomLogin = (ImageView)layout.findViewById(R.id.image_view_pic_belom_login);
//        mTextViewBelomLogin = (TextView)layout.findViewById(R.id.tessss);

        mTextError = (TextView)layout.findViewById(R.id.textError);
        mSwipeRefreshLayoutFavorite = (SwipeRefreshLayout)layout.findViewById(R.id.swipeFavorite);
        mSwipeRefreshLayoutFavorite.setOnRefreshListener(this);
        mRecylerFavoriteProduct = (RecyclerView)layout.findViewById(R.id.listFavorite);

        mLayoutManager = new GridLayoutManager(getActivity(),2);
        mRecylerFavoriteProduct.setLayoutManager(mLayoutManager);
        mAdapter = new AdapterFavorite(getActivity());
        mRecylerFavoriteProduct.setAdapter(mAdapter);


        TaskFavorite taskFavorite;
//        if (authenticate()==true){
//            mImageViewBelomLogin.setVisibility(View.GONE);
//            mButtonLogin.setVisibility(View.GONE);
//            mTextViewBelomLogin.setVisibility(View.GONE);
            taskFavorite = new TaskFavorite(getActivity());
            taskFavorite.getFavoritesDataInBackground(new GetFavoritesCallback() {
                @Override
                public void onGetFavoritesLoadedListener(ArrayList<ProductFavorite> listFavorites) {
                    mListFavorites = listFavorites;
                    Toast.makeText(context, ""+mListFavorites.size(), Toast.LENGTH_SHORT).show();
                    mAdapter.setListFavorite(mListFavorites);
                }
            });
//        }




        return layout;
    }


    private boolean authenticate() {
        return userController.getUserLoggedIn();
    }

    @Override
    public void onRefresh() {
        TaskFavorite taskFavorite;
        taskFavorite = new TaskFavorite(getActivity());
        taskFavorite.getFavoritesDataInBackground(new GetFavoritesCallback() {
            @Override
            public void onGetFavoritesLoadedListener(ArrayList<ProductFavorite> listFavorites) {
                mListFavorites = listFavorites;
                Toast.makeText(context, ""+mListFavorites.size(), Toast.LENGTH_SHORT).show();
                mAdapter.setListFavorite(mListFavorites);
            }
        });
    }
}
